name: calcpal
description: CalcPal is a specialized educational app designed to support individuals with Dyscalculia, a specific learning disorder that affects a person's ability to understand and perform mathematical operations. With tailored exercises and interactive features, CalcPal aims to empower users to improve their arithmetic skills and build confidence in math.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  # Flutter SDK for core Flutter framework
  flutter:
    sdk: flutter

  # Internationalization and localization support
  intl: ^0.19.0

  # SVG image rendering support
  flutter_svg: ^2.0.10+1

  # Environment variable management
  flutter_dotenv: ^5.1.0

  # Speech-to-text functionality
  speech_to_text: ^6.6.1

  # HTTP client for network requests
  http: ^1.2.1

  # Toast notifications for user feedback
  toastification: ^2.1.0

  # Launcher icon customization
  flutter_launcher_icons: "^0.13.1"  

  # iOS style icons
  cupertino_icons: ^1.0.2

  # Microsoft Azure Text-to-Speech functionality
  cloud_text_to_speech: ^1.1.3

  # Audio playback
  audioplayers: ^6.0.0

  # Customizable loading indicators
  flutter_spinkit: ^5.2.1

  # A package for storing simple data such as user preferences
  shared_preferences: ^2.3.2

  # A package for decoding JWT tokens and checking expiration
  jwt_decoder: ^2.0.1

dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Flutter lints for code quality
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  # Configuration for customizing app launcher icons for both Android and iOS
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login_background.png
    - assets/images/main_dashboard_background.png
    - assets/images/diagnose_quiz_1.png
    - assets/images/diagnose_quiz_2.png
    - assets/images/diagnose_quiz_3.png
    - assets/images/diagnose_quiz_4.png
    - assets/images/diagnose_background_v1.png
    - assets/images/diagnose_background_v2.png
    - assets/images/diagnose_result_background.png
    - assets/images/diagnose_report_background.png

    - assets/icons/user.svg
    - assets/icons/email.svg
    - assets/icons/cake.svg
    - assets/icons/closed-eye.svg
    - assets/icons/open-eye.svg
    - assets/icons/back.png
    - assets/icons/profile.png
    - assets/icons/play-button.svg
    - assets/icons/pause-button.svg
    - assets/icons/microphone.svg
    - assets/icons/microphone-radio.svg
    - assets/icons/well-done.png

    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Aclonica
      fonts:
        - asset: assets/fonts/Aclonica-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
